### ISSUE TITLE
[BUG] UI webview shouldn't offer translation

### ISSUE THREAD

**Issue by thatfloflo** [lart-bangor/research-assistant#45]
**Describe the bug**
Currently, especially upon first install and run, Chrome/Chromium/Edge even in app mode might prompt users if they want to use Google or Bing translation to translate the UI, which leads to very poor quality UI translations and potentially introduces confounds.

**Expected behavior**
UI elements should never offer translations via the webview component. They should probably be marked as "notranslate" at the top of the DOM hierarchy.

**System information:**
 - Device: any
 - OS: any
 - Version: any

**Comment by ashish-khankari** [comment]
Could You assign me this task, I would love to contribute and please describe in detail about issue

**Comment by thatfloflo** [comment]
Thank you for offering to tackle this @ashish-khankari - I've assigned it to you and we'll be happy to receive a corresponding PR. If  any questions pop up in the process feel free to ask (I know the [Developer Guide](https://lart.readthedocs.io/projects/research-assistant/en/latest/developers/index.html) is still lacking a bit!)
