### ISSUE TITLE
wrong image / path in localisation tutorial [BUG] 

### ISSUE THREAD

**Issue by dakrismeno** [lart-bangor/research-assistant#65]
**Describe the bug**
Instruction on Localisation have image with wrong path for versions

**To Reproduce**
1. Go to: https://lart.readthedocs.io/projects/research-assistant/en/latest/tutorials/localisation-translations.html
2. Scroll down to "Creating and Naming your file"
3. See error

**Expected behavior**
Path should be: C:\Users\USERNAME\AppData\Local\Programs\LART\Research Client\research_assistant\lsbq\versions

**Screenshots**
![image](https://github.com/lart-bangor/research-assistant/assets/99651949/b50d5010-ff9d-41a3-86e7-46335ad13486)

**Comment by thatfloflo** [comment]
Fixed in [e7d9e3eb](https://github.com/lart-bangor/research-assistant/commit/e7d9e3ebb7d135b0e769df0dbdd9d2681635b8f6)
